export const ClientActionTypes = {
    ADD_HOUSE_CART: 'ADD_HOUSE_CART',
    ADD_COMPLETED_HOUSE_CART: 'ADD_COMPLETED_HOUSE_CART',
    ADD_INVESTORS_HOUSE_CART: 'ADD_INVESTORS_HOUSE_CART',

    SET_SORT_BY: 'SET_SORT_BY',
    SET_CATEGORY: 'SET_CATEGORY',
    SET_COST: 'SET_COST',
    SET_SQUARE: 'SET_SQUARE',
    SET_FILTER_COST: 'SET_FILTER_COST',
    SET_FILTER_SQUARE: 'SET_FILTER_SQUARE',

    GET_PROJECT_ID: 'GET_PROJECT_ID',
    GET_PROJECT_PAGE_INFO: 'GET_PROJECT_PAGE_INFO',

    SET_COMPLETED_PROJECTS: 'SET_COMPLETED_PROJECTS',
    SET_COMPLETED_HOUSES: 'SET_COMPLETED_HOUSES',
    SET_INVESTORS_HOUSES: 'SET_INVESTORS_HOUSES',
    SET_POST_INFO: 'SET_POST_INFO',
    SET_POST_COST: 'SET_POST_COST',
    SET_HEART_ID: 'SET_HEART_ID',
    SET_HOUSE_HEART_ID: 'SET_HOUSE_HEART_ID',
    SET_INVEST_HEART_ID: 'SET_INVEST_HEART_ID',
    SET_PROJECTS_PAGE: 'SET_PROJECTS_PAGE',
    SET_HOUSES_PAGE: 'SET_HOUSES_PAGE',
    SET_INVESTS_PAGE: 'SET_INVESTS_PAGE',
}