export const ActionTypes = {
  SET_ITEM: 'SET_STORE_ITEM',
  ALERT: 'ALERT_VALUES',
  ADMINS_DATA: 'ADMINS_DATA',
  CURRENT_ADMIN: 'CURRENT_ADMIN',
  NEW_ADMIN: 'NEW_ADMIN',
  REF_FORM: 'REF_FORM',
  RIGHTS_CODE: 'RIGHTS_CODE'
}
